on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}

    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v4
      - name: Check rust code "${{ matrix.BUILD_TARGET }}" mode
        run: cargo check
      - name: Build Linux binary in "${{ matrix.BUILD_TARGET }} mode"
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      - name: Upload release artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: rust-emulas-linux
          path: target/${{ matrix.BUILD_TARGET }}
