on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]

    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check if src folder has changes
        id: changes
        run: |
          echo "Checking changes in src/..."
          git fetch origin ${{ github.event.before }}
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^src/' || true)
          if [ -n "$CHANGED_FILES" ]; then
            echo "build_needed=true" >> $GITHUB_ENV
          else
            echo "build_needed=false" >> $GITHUB_ENV
          fi

      - name: Check rust code "${{ matrix.BUILD_TARGET }}" mode
        if: env.build_needed == 'true'
        run: cargo check

      - name: Build Linux binary in "${{ matrix.BUILD_TARGET }} mode"
        if: env.build_needed == 'true'
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}

      - name: Upload release artifact (Linux)
        if: env.build_needed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: rust-emulas-linux
          path: target/${{ matrix.BUILD_TARGET }}
